version: '3'
  services:
    pi_tree:
      container_name: pi-tree
      image: robvangeloven/pi-tree
      devices:
        - /dev/gpiomem:/dev/gpiomem
      volumes:
        - /PATH_TO_YOUR_CONFIG:/config
      restart: always
      network_mode: host