version: '3.4'

services:
  pi_tree:
    image: ${DOCKER_REGISTRY-}pi-tree
    build:
      context: .
      dockerfile: PiTree/Dockerfile
    container_name: pi-tree
    volumes:
      - /PATH_TO_YOUR_CONFIG:/app/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/gpiomem:/dev/gpiomem
    restart: always
    network_mode: host