version: '3'
  services:
    pi_tree:
      container_name: pi-tree
      image: homeassistant/home-assistant
      volumes:
        - /PATH_TO_YOUR_CONFIG:/app/config
        - /etc/localtime:/etc/localtime:ro
      devices:
        - /dev/gpiomem:/dev/gpiomem
      restart: always
      network_mode: host